---
header-includes:
  - \setmainfont{Times New Roman}
  - \usepackage{zxjatype} # 日本語を使うためのパッケージ
  - \setjamainfont{Hiragino Mincho ProN} # 日本語フォントの指定
  - \usepackage{fouriernc} # 立体のギリシア文字など
  - \usepackage{lscape} # 図を回転するためのパッケージ
  - \newcommand{\blandscape}{\begin{landscape}} # 図回転用のbegin command
  - \newcommand{\elandscape}{\end{landscape}} # 図回転用のend command
  - \usepackage{setspace} # 行間の調節ためのパッケージ
  - \newcommand{\bdoublespace}{\begin{spacing}{1.5}} # 行間を広げるbegin command
  - \newcommand{\edoublespace}{\end{spacing}{}} # 行間を広げるbegin command


output:
  pdf_document:
    latex_engine: xelatex

---

\large
\bdoublespace

安武 大輔 先生

  丁寧な編集ありがとうございます。
  以下にコメントに対する対応を記載いたします。
  原稿中に今回変更した箇所を青文字で示しております。
  同赤文字は初回の査読の際の変更箇所です。
  ご確認くださるよう、よろしくお願いいたします。

村上 貴一

------

[Editor's Comments]

基本的には、コメントに対して、適切に対応しており、掲載可として結構だと思いますが、
2点ほど、著者自身によって確認をして頂きたい点があります。

１．”statistical interaction”について
あまり聞かない表現のような気がします。特に、今回、統計的手法（例えば回帰分析など）を使用して解析されているわけではありませんので、変数間の関係を示す”statistical interaction”の使用が、かえって、読者が混乱する可能性があります。そこで、以下を提案します。
使用する語句は　“statistical interaction”ではなく、“interaction”として、それが、一般的なinteraction（相互で作用し合うこと）ではなく、“あるもののへの複合的な影響（combined effect、統計的には交互作用?）”を意味していることを、なるべく判りやすくする。
本文中には（61行目から）、The effect of the relative spectral distribution of growth light on Pn depends on the distribution of measuring light. とあり、その後のinteractionは、後者の意味として捉えることができるかもしれません。しかし、abstractにおける以下の部分は、いきなり出てくるので、変更が必要かもしれません。
L10, ”  but also affect it indirectly through interaction with the spectral distribution”
上記の意見を参考に、修正ができる場合は、修正して下さい（著者が修正必要なしと判断される場合は、修正なしで結構です）。

> “statistical interaction”というフレーズを除きました (line 11, 62)。
> また、ご指摘いただいた要旨部分について、“相互に作用する”のではなく、“複合的に影響を及ぼすこと”、が明確になるよう、変更を加えました (line 10)。

２．Fig.3について
　前回の査読者の指摘の繰り返しになりますが、この図の問題点は、概念図といいつつ、グラフ（散布図：x,yともに定量的）にしていることで、定量的な意味合いがあるかのように取れることです。それを意図されているのなら、結構ですが、ここで言えることは、基本的には、Fig.2を使っても言える気がします。すなわち、Fig.2以上に定量的な意味を付加しないのであれば、必要なしというのが、査読者の意見だと思います。
　また、もう一度、確認して頂きたいのは、曲線の形です。これには意味がありますか？あえて（正当な理由があって）、左右対称にしていないのなら、良いのですが、そうでないとしたら、再考願います。
　上記を考慮し、再度、この図が必要かどうか、ご判断下さい。再考慮後、このままで、ということであれば、それでも結構です。

> 前回・今回のご意見を反映し、必要ではないためFig.3を削除いたしました (line 153)。
> 旧Fig.4をFig.3へ繰り上げることに伴う修正を行いました (line, 184, 196, 342)。  
> 蛇足かもしれませんが、前回の査読に適切に対応できていなかった曲線の形について  
> 横軸が順序尺度であり、曲線の形には絶対的な意味はありません。
> その意味で"概念図"としていました。
> $\otherbeta_\textrm{PS}$あるいはPFD~FR~/PPFDのような比例尺度を横軸にとると、各々の線は左右非対称になることが予想されますが、それを検証できるデータがないので、定量的な図示を避けております。

\edoublespace